### ISSUE TITLE
Does this work with the Redis engine?

### ISSUE THREAD

**Issue by michaelmarconi** [jamesotron/faye-rails#1]
Hi - I'm hoping to use this in conjunction with the Redis engine (https://github.com/faye/faye-redis-ruby).  I don't think that's possible with `faye-rails` right now, since the `require 'faye/redis'` statement needs to appear somewhere.

Can you suggest a way of bringing the Redis engine in please?

Many thanks,
Michael

**Comment by gabrieltong** [comment]
+1
