### ISSUE TITLE
Faye.ensure_reactor_running! in an initializer

### ISSUE THREAD

**Issue by nilbus** [jamesotron/faye-rails#26]
Hi, I noticed your [recent change to the README](https://github.com/jamesotron/faye-rails/commit/3b10e2958f3f50419457d222b19c37b7cb3cb521#L0R135) in which you recommended an initializer to run `Faye.ensure_reactor_running!`. I've actually tried this before with no luck. When I try to start a server in development mode, it just exits during the app startup like so.

```
$ rails server
=> Booting Thin
=> Rails 4.0.0.beta application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:3000, CTRL+C to stop
Exiting
```

Have you gotten ensure_reactor_running! working in one of your own apps?

**Comment by habitullence** [comment]
@jamesotron I'm not sure if this is the same issue but I'm getting the error ```eventmachine not initialized: evma_install_oneshot_timer (RuntimeError)``` when running Cucumber. I've added the initializer you suggested.

**Comment by habitullence** [comment]
Never mind, it's because Cucumber doesn't load initialisers. To get it working I just needed to add ```Faye.ensure_reactor_running!``` to a support file, e.g., support/faye.rb.
