### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by bodrovis** [jamesotron/faye-rails#35]
Hello. I am using Faye with Rails 3.2.12 to implement comments that are instantly showing up. Everything is working fine, however I get some errors in the Firebug console. When i open the page the POST request is being sent to "http://mydomain.com/faye" with the following response:

```
[{"id":"1","channel":"/meta/handshake","successful":true,"version":"1.0","supportedConnectionTypes":["long-polling","cross-origin-long-polling","callback-polling","websocket","eventsource","in-process"],"clientId":"j1ezqdmr62rap6njeqv7u21kj2nndw1","advice":{"reconnect":"retry","interval":0,"timeout":25000}}]
```

But right after this appears an error
```
"NetworkError: 400 Bad Request - http://mydomain.com/faye"
```

Then another POST request is again sent to the "http://mydomain.com/faye" with reponse like:
```
[{"id":"2","clientId":"j1ezqdmr62rap6njeqv7u21kj2nndw1","channel":"/meta/subscribe","successful":true,"subscription":"/comments"},{"id":"3","clientId":"j1ezqdmr62rap6njeqv7u21kj2nndw1","channel":"/meta/connect","successful":true,"advice":{"reconnect":"retry","interval":0,"timeout":25000}}]
```
Then another two errors appears:

```
Firefox can't establish a connection to the server at ws://mydomain.com/faye.
```
and
```
"NetworkError: 404 Not Found - http://mydomain.com/faye/j1ezqdmr62rap6njeqv7u21kj2nndw1/j1ezqdmr62rap6njeqv7u21kj2nndw1"
```

After these errors follow succesfull POST requests to the "http://mydomain.com/faye" with responses like:
```
[{"id":"5","clientId":"j1ezqdmr62rap6njeqv7u21kj2nndw1","channel":"/meta/connect","successful":true,"advice":{"reconnect":"retry","interval":0,"timeout":25000}}]
```

I get all these errors in production (Heroku).

Still the comments are being updated instantly and I detect no other errors or problems.

In my route file I get:

```ruby
  faye_server '/faye', :timeout => 25
```
Am I doing something wrong or did I forget something?

Thanks!

**Comment by Praveen-Invoscape** [comment]
@bcavileer @bodrovis  i am also have this issue bad request for "https://mydomain.herokuapp.com/faye" for my domain.I am new to rails so plz explain to use your answer

**Comment by bodrovis** [comment]
@Praveen-Invoscape I have not used faye in quite a while, mainly because Rails 5 now has ActionCable. That line should be added into your JS or CoffeeScript file, but things may have changes during these years so it may not be needed. Also, your error may be related to something else. By the way, here is my article on Faye that may come in handy https://www.sitepoint.com/realtime-mini-chat-rails-faye/

**Comment by bodrovis** [comment]
@Praveen-Invoscape Also do note that now Heroku does support websockets - at least I had no problems with ActionCable.

**Comment by Praveen-Invoscape** [comment]
Thank you @bodrovis  i will try to fix it by your link
