### ISSUE TITLE
Passenger support is broken

### ISSUE THREAD

**Issue by stas-sl** [jamesotron/faye-rails#58]
It seems that this condition was deleted during merge (0773e007ed56fa43da3164885ddd9f4e8b78a3f5) from `middleware.rb`:

``` ruby
Faye::WebSocket.load_adapter(server) if server && server != 'passenger'
```

So it tries to load passenger adapter, but it doesn't exist.

**Comment by dduft** [comment]
Will there be a new version for this?

**Comment by jamesotron** [comment]
Can someone confirm that it actually works first?

**Comment by varun-raj** [comment]
Any update ?

**Comment by deepsystm** [comment]
+ @varun-raj

**Comment by deepsystm** [comment]
it solves by
```
gem 'faye-rails', github: 'jamesotron/faye-rails'
```

**Comment by jamesotron** [comment]
Awesome. I'll bump and release.
