### ISSUE TITLE
Outdated technology information

### ISSUE THREAD

**Issue by Epigene** [jamesotron/faye-rails#78]
Readme states "Due to the limitations of most Rack-based web servers available Faye can only be run on Thin".
However it is my understanding that Faye has added support for many more web servers that support rack.hijack, especially puma, [as discussed here](https://github.com/faye/faye-websocket-ruby/issues/17).
Time for an update on this issue?

**Comment by jamesotron** [comment]
You're probably right. I'd definitely accept a PR that updates this information. Cheers :+1:
